/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applications;

import streameditor.StreamingTextArea;
import basic_3_c64.CommandLineDispatcher;
import buildnum.BuildInfo;
import misc.MDIChild;
import misc.Misc;

import javax.swing.*;
import javax.swing.event.InternalFrameListener;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.concurrent.*;

/**
 *
 * @author Administrator
 */
public class CBMGui extends MDIChild implements Runnable, ActionListener, InternalFrameListener
{
    public StreamingTextArea area = new StreamingTextArea(); //javax.swing.JTextArea area;

    private final CommandLineDispatcher dispatcher = new CommandLineDispatcher(this);

    public FutureTask<?> basicTask;
    public long threadID;

    /* sleep/wakeup map */
    public static final
    ConcurrentHashMap<Long, CountDownLatch> latchMap = new ConcurrentHashMap<>();
    public static final
    ConcurrentHashMap<Long, StreamingTextArea> streamMap = new ConcurrentHashMap<>();

    private boolean cbDirectInsertFlag;

    {
        initComponents();
    }

    public CompletableFuture<Long> _fut;

    /**
     * Creates new form NewJInternalFrame
     */
    public CBMGui (CompletableFuture<Long> fut)
    {
        super();
        _fut = fut;
        basicTask = Misc.execute(this); //FutureTask<?>) executor.submit(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        comboBox = new JComboBox<>();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        //setTitle("BASIC -- " + );
        setVisible(true);
        addInternalFrameListener(this);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("CLS");
        jButton1.addActionListener(this);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setText("Stop");
        jButton2.addActionListener(this);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        comboBox.addActionListener(this);
        jPanel1.add(comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        area.setBackground(new java.awt.Color(0, 0, 153));
        area.setForeground(new java.awt.Color(255, 255, 102));
        area.setColumns(20);
        area.setFont(new java.awt.Font("Monospaced", Font.PLAIN, 16)); // NOI18N
        area.setLineWrap(true);
        area.setRows(20);
        area.setCaretColor(new java.awt.Color(255, 102, 102));
        area.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(area);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }

    public synchronized void setLineInList (java.lang.String s)
    {
        SwingUtilities.invokeLater(() ->
        {
            if(((DefaultComboBoxModel<String>)comboBox.getModel()).getIndexOf(s) != -1)
            {
                return;  // item already in here
            }
            comboBox.insertItemAt (s, 0);
            cbDirectInsertFlag = true;
            comboBox.setSelectedIndex (0);
        });
    }

    public void actionPerformed(java.awt.event.ActionEvent evt)
    {
        if (evt.getSource() == jButton1)
        {
            CBMGui.this.jButton1ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton2)
        {
            CBMGui.this.jButton2ActionPerformed(evt);
        }
        else if (evt.getSource () == comboBox)
        {
            if (cbDirectInsertFlag) // Not a real event
            {
                cbDirectInsertFlag = false;
            }
            else
            {
                String s = comboBox.getItemAt (comboBox.getSelectedIndex ());
                area.fakeIn (s+'\n');
            }
        }
    }

    public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt)
    {
    }

    public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt)
    {
        if (evt.getSource() == CBMGui.this)
        {
            CBMGui.this.formInternalFrameClosed(evt);
        }
    }

    public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt)
    {
    }

    public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt)
    {
    }

    public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt)
    {
    }

    public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt)
    {
    }

    public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt)
    {
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Window closed
     *
     * @param evt
     */
    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        dispatcher.basicRunner.getOlsenBasic().runStop();
        //area.fakeIn("bye\n");  // Force basicThread to end if no pg runs
    }//GEN-LAST:event_formInternalFrameClosed

    // cls
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        area.setText("\n>");
    }//GEN-LAST:event_jButton1ActionPerformed

    // stop running prg
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // end possible wait state
        //basicTask.cancel(true);
        area.interrupt();
        dispatcher.basicRunner.getOlsenBasic().runStop();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private JComboBox <java.lang.String> comboBox;
    //private javax.swing.JTextField saveName;
    // End of variables declaration//GEN-END:variables

    /**
     * runs the command line interpreter
     * @return 1 if GUI closed. otherwise 0
     */
//    private void runBasicSystem ()
//    {
//        System.err.println("run BASIC system ...");
//        area.requestFocus();
//    }

    @Override
    public void run()
    {
        Thread.currentThread().setPriority(Thread.MIN_PRIORITY);
        System.out.println("Basic Thread start");
        threadID = Thread.currentThread().getId();
        SwingUtilities.invokeLater(() -> setTitle("BASIC Thread:" + threadID));

        area.requestFocus();
        System.err.println("run BASIC system ...");
        area.getPrintStream().println (BuildInfo.buildInfo);
        //runBasicSystem();

//        //basic.getOlsenBasic().runStop();
//        latchMap.remove(threadID);
//        streamMap.remove(threadID);
//        SwingUtilities.invokeLater (this::dispose);
//        System.out.println("BasicThread end");
    }
}
