package applications;

import misc.ClipboardImage;
import misc.MDIChild;

import javax.swing.*;
import java.awt.*;
import java.util.concurrent.CompletableFuture;

public class DrawingGUI extends MDIChild //JFrame
{
    public Canvas canvas;
    private JPanel mainPanel;
    private JButton clipButton;
    private JButton wipeButton;

    public static void main(String[] args)
    {
        DrawingGUI frame = new DrawingGUI(null);
    }

    public DrawingGUI(CompletableFuture<Long> dummy)
    {
        super();

        clipButton.addActionListener(e -> new ClipboardImage(canvas.off_Image));
        wipeButton.addActionListener(e -> canvas.clear());

        setContentPane (mainPanel);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Plot Window: " + Thread.currentThread().getId());
        setSize(500, 500);
        setVisible(true);
    }

    private void createUIComponents()
    {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.setBackground(new Color(-7264487));
        panel1.setForeground(new Color(-12961025));
        mainPanel.add(panel1, BorderLayout.SOUTH);
        clipButton = new JButton();
        clipButton.setText("toClip");
        panel1.add(clipButton);
        wipeButton = new JButton();
        wipeButton.setText("Wipe");
        panel1.add(wipeButton);
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, BorderLayout.CENTER);
        canvas = new Canvas();
        canvas.setLayout(new BorderLayout(0, 0));
        canvas.setBackground(new Color(0));
        canvas.setPreferredSize(new Dimension(1024, 1024));
        scrollPane1.setViewportView(canvas);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
